#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
java -Dswing.defaultlaf=javax.swing.plaf.nimbus.NimbusLookAndFeel -jar "$DIR/${project.artifactId}-${project.version}-jar-with-dependencies.jar" "$@"
