#!/bin/bash
echo "Running Installer"
cp -r compi-gui/* /usr/local/bin
if (( $? )); then
  echo "Error during compi-gui installation" >&2
  exit 1
else
  echo "Installation successful. Type compi-gui to start!"
fi
