#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
$DIR/compi-gui-files/jre/bin/java -Dswing.defaultlaf=javax.swing.plaf.nimbus.NimbusLookAndFeel -jar "$DIR/compi-gui-files/${project.artifactId}-${project.version}-jar-with-dependencies.jar" "$@"
